### ISSUE TITLE
model parameter 

### ISSUE THREAD

**Issue by Yzichen** [Guillem96/spynet-pytorch#1]
I  download the .pt file, but the content is 
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>

how should i do?

**Comment by Guillem96** [comment]
Sorry @jiu-jian-xian I cqnnot maintain the GCP ptoject with the Stoarage bucket containing the model weights.

I have to migrate thia to GDrive to provide the weights for free
